services:
  backend:
    build: .
    container_name: fraud-backend
    ports:
      - "8000:8000"

  frontend:
    image: python:3.11-slim
    container_name: fraud-frontend
    depends_on:
      - backend
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install streamlit requests && streamlit run frontend.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
